name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Image Tag
        run: |
          echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/mateszadam/proceccors-list:$IMAGE_TAG --tag ghcr.io/mateszadam/proceccors-list:latest
          docker login ghcr.io -u mateszadam -p ${{secrets.GHCL_TOKEN}}
          docker push ghcr.io/mateszadam/proceccors-list:$IMAGE_TAG
          docker push ghcr.io/mateszadam/proceccors-list:latest
